require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - .git/**/*
    - bin/**/*
    - db/schema.rb
    - db/migrate/20220919175810_devise_create_users.rb
    - db/migrate/20220922194654_devise_invitable_add_to_users.rb
    - db/migrate/20220926213444_create_active_storage_tables.active_storage.rb
    - db/migrate/20220928165917_add_task_list_reference_to_task.rb
    - db/migrate/20221003232158_add_authorization_tier_and_name_to_user.rb
    - app/controllers/invitations_controller.rb
    - app/controllers/users/*

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - config/initializers/devise.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
